# Site settings
logo:
title: Orchard
alternateTitle:
description: >- # this means to ignore newlines until "image"
  A way to share the Word of God to those who happen upon this place.
image:
repository: orchardcc/orchard.cc

# Social settings
email: email@orchard.cc
facebook:
twitter:

# Pagination settings
pagination:
  items: 5
  links: 5

# Jekyll settings
permalink: /:collection/:categories/:year/:month/:day/:title

# Collections settings
collections:
  bible:
    output: true

# Front matter default settings
defaults:
  -
    scope:
      path: "_bible/person"
      type: "bible"
    values:
      layout: "page"
      include: genealogy.html
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-remote-theme
  - jekyll-sitemap
remote_theme: orchardcc/jekyll-theme-orchard
