# Site settings
logo:
title: Orchard
alternateTitle:
description: >- # this means to ignore newlines until "image"
  A way to share the Word of God to those who happen upon this place.
image: 
repository: orchardcc/orchardcc.github.io

# Social settings
email: email@orchard.cc
facebook:
twitter:

# Jekyll settings
permalink: /:categories/:year/:month/:day/:title

# Collections settings
collections:
  bible:
    output: true

# Front matter default settings
defaults:
  -
    scope:
      path: "_bible"
      type: "bible"
    values:
      layout: "page"
  -
    scope:
      path: "_bible/person"
      type: "bible"
    values:
      layout: "page"
      include: genealogy.html

# Build settings
markdown: kramdown
plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme
remote_theme: orchardcc/jekyll-theme-orchard
