# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server
# process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: bromidr
logo: https://www.github.com/bromidr.png
description: >- # this means to ignore newlines until "baseurl:"
  A way to share the Word of God to those who happen upon this place
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bromidr.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:year-:month-:day-:title

# Social settings
repository: bromidr/bromidr.github.io
facebook: bromidr
instagram: bromidr
twitter: bromidr
email: info@bromidr.com

# Collections and default settings
collections:
  viz:
    output: true
  category:
    output: true
  author:
    output: true

defaults:
  -
    scope:
      path: "_viz"
      type: "viz"
    values:
      layout: "viz"
  -
    scope:
      path: "_category"
      type: "category"
    values:
      layout: "archive"
  -
    scope:
      path: "_author"
      type: "author"
    values:
      layout: "archive"
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      authors: [Bromide Roach]

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
