name: 'Jekyll Build and Deploy to GitHub Pages'
description: 'Build Jekyll site and deploy to the master or gh-pages branch of repository'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cast'
  color: 'purple'
